import { prisma } from "../../../src/lib/prismaClient";

export const generateReportSchema = {
  type: "function" as const,
  function: {
    name: "generate_recovery_report",
    description: "Generate a comprehensive markdown-formatted payment recovery report for a time period.",
    parameters: {
      type: "object",
      properties: {
        period_days: { type: "number", description: "Number of past days to include in the report (default 7)" },
      },
      required: [],
    },
  },
};

export async function executeGenerateReport(args: { period_days?: number }): Promise<{ report: string }> {
  const days = args.period_days ?? 7;
  const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  const now = new Date();

  const events = await prisma.failureEvent.findMany({
    where: { detectedAt: { gte: since } },
    include: {
      recoveryActions: true,
      payment: { include: { order: { include: { product: { select: { name: true } } } } } },
    },
    orderBy: { detectedAt: "desc" },
  });

  const total = events.length;
  const recovered = events.filter((e) => e.recoveryActions.some((a) => a.outcome === "success"));
  const atRisk = events.filter((e) => !e.recoveryActions.some((a) => a.outcome === "success"));
  const pending = events.filter((e) => e.recoveryActions.length === 0);

  const totalRecoveredPaise = recovered.reduce((s, e) => s + (e.payment?.order?.amount ?? 0), 0);
  const totalAtRiskPaise = atRisk.reduce((s, e) => s + (e.payment?.order?.amount ?? 0), 0);
  const recoveryRatePct = total > 0 ? ((recovered.length / total) * 100).toFixed(1) : "0.0";

  // Category breakdown
  const catMap: Record<string, { count: number; amount: number }> = {};
  for (const e of events) {
    const cat = e.classifiedCategory;
    if (!catMap[cat]) catMap[cat] = { count: 0, amount: 0 };
    catMap[cat].count++;
    catMap[cat].amount += e.payment?.order?.amount ?? 0;
  }
  const catRows = Object.entries(catMap)
    .sort((a, b) => b[1].count - a[1].count)
    .map(([cat, s]) => `| ${cat.replace(/_/g, " ")} | ${s.count} | \u20b9${Math.round(s.amount / 100).toLocaleString("en-IN")} |`)
    .join("\n");

  // Recovery proof entries
  const proofRows = recovered.slice(0, 10).map((e) => {
    const action = e.recoveryActions.find((a) => a.outcome === "success");
    const amt = Math.round((e.payment?.order?.amount ?? 0) / 100).toLocaleString("en-IN");
    return `| ${e.classifiedCategory.replace(/_/g, " ")} | \u20b9${amt} | ${action?.actionType?.replace(/_/g, " ") ?? "—"} | ${action?.channel ?? "—"} | \u2713 Recovered |`;
  }).join("\n");

  const fmt = (d: Date) => d.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

  const report = `# Payment Recovery Report
**Period:** ${fmt(since)} – ${fmt(now)} (last ${days} days)
**Generated:** ${fmt(now)}

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Failure Events | ${total} |
| Successfully Recovered | ${recovered.length} |
| Still At Risk | ${atRisk.length} |
| Pending Recovery | ${pending.length} |
| **Revenue Recovered** | **\u20b9${Math.round(totalRecoveredPaise / 100).toLocaleString("en-IN")}** |
| Revenue At Risk | \u20b9${Math.round(totalAtRiskPaise / 100).toLocaleString("en-IN")} |
| **Recovery Rate** | **${recoveryRatePct}%** |

---

## Failure Category Breakdown

| Category | Events | Amount Lost |
|----------|--------|-------------|
${catRows || "| No data | — | — |"}

---

## Recovery Proof (Recent Successes)

| Category | Amount | Action | Channel | Outcome |
|----------|--------|--------|---------|---------|
${proofRows || "| No successful recoveries in this period | — | — | — | — |"}

---

## Audit Trail Note

All recovery actions were executed by the AI Recovery Agent with full logging. Agent reasoning is stored in the database for compliance. No customer PII was shared externally.

*Report generated by Merchant Intelligence Agent.*`;

  return { report };
}
